aceweb/views/clients.py
from flask import Blueprint, render_template, redirect, url_for, session, request, flash, jsonify
from configparser import ConfigParser
import subprocess as sb

from core.utils_flask import logged_in, flash_errors
from core.globals import Global
from core.utils import HostapdCli, readSectionlessConfig, getPID

clients = Blueprint( "clients", __name__)

@clients.route("/")
@logged_in
def show_clients():
    client_filters = {}

    hostapd_conf = ConfigParser()
    hostapd_conf.readfp( readSectionlessConfig("root", Global.CONFIG_DIR + "/hostapd.conf") )

    if "macaddr_acl" in hostapd_conf["root"]:
        client_filters["mode"] = hostapd_conf["root"]["macaddr_acl"]

        # listing macs in accept list
        accept_list = ConfigParser(strict=False, allow_no_value=True, delimiters=(' '))
        accept_list.readfp( readSectionlessConfig("root", Global.CONFIG_DIR + "/hostapd.accept") )
        client_filters["accept_list"] = list(accept_list["root"])

        # listing macs in deny list
        deny_list = ConfigParser(strict=False, allow_no_value=True, delimiters=(' '))
        deny_list.readfp( readSectionlessConfig("root", Global.CONFIG_DIR + "/hostapd.deny") )
        client_filters["deny_list"] = list(deny_list["root"])

    else:
        client_filters = None

    # connected client to rougeap
    connect_clients = []
    if getPID("hostapd") !=-1:
        BIN_HOSTAPDCLI = Global.EXTERNAL_TOOLS_DIR + "/hostapd-mana/hostapd/hostapd_cli"
        connect_clients = HostapdCli.listConnected( BIN_HOSTAPDCLI, "/tmp/aceweb/dnsmasq.leases" )

    return render_template("clients.html", client_filters = client_filters, connect_clients=connect_clients)

@clients.route("/change_filter_mode", methods=["GET"])
@logged_in
def change_filter_mode():
    if "mode" not in request.args:
        return jsonify(message="mode not specified."), 400

    mode = str(request.args.get("mode"))

    sb.call(["sed", "-i", "s/macaddr_acl=.*/macaddr_acl=" + mode + "/" , Global.CONFIG_DIR + "/hostapd.conf"])

    return jsonify(message="mode changed " + mode)


@clients.route("/add_to_filter", methods=["GET"])
@logged_in
def add_to_filter():
    if "mac" not in request.args:
        return jsonify(message="mac not specified."), 400

    if "file" not in request.args:
        return jsonify(message="file not specified."), 400


    mac = str(request.args.get("mac"))
    mac = mac + " " + mac
    file_name = str(request.args.get("file"))

    if file_name == "accept":
        check = sb.Popen(["grep", mac, Global.CONFIG_DIR + "/hostapd.accept"], stdout=sb.PIPE).stdout.read()
        if len(check)==0:
            with open(Global.CONFIG_DIR + "/hostapd.accept", "a") as f:
                f.write(mac + "\n")
        else:
            return jsonify(message="Already exists : " + mac), 400

    elif file_name == "deny":
        print "DENY"
        check = sb.Popen(["grep", mac, Global.CONFIG_DIR + "/hostapd.deny"], stdout=sb.PIPE).stdout.read()
        if len(check)==0:
            with open(Global.CONFIG_DIR + "/hostapd.deny", "a") as f:
                f.write(mac + "\n")
        else:
            return jsonify(message="Already exists : " + mac), 400

    else:
        return jsonify(message="invailed filed specified : " + file_name ), 400

    return jsonify(message="Added to " +file_name+ " list : " + mac)


@clients.route("/remove_from_filter", methods=["GET"])
@logged_in
def remove_from_filter():
    if "mac" not in request.args:
        return jsonify(message="mac not specified."), 400

    if "file" not in request.args:
        return jsonify(message="file not specified."), 400


    mac = str(request.args.get("mac"))
    file_name = str(request.args.get("file"))

    if file_name == "accept":
        sb.call(["sed", "-i", "s/^" + mac + ".*$//Ig", Global.CONFIG_DIR + "/hostapd.accept"])

    elif file_name == "deny":
        sb.call(["sed", "-i", "s/^" + mac + ".*$//Ig", Global.CONFIG_DIR + "/hostapd.deny"])
    else:
        return jsonify(message="invailed filed specified : " + file_name ), 400

    return jsonify(message="Removed from " +file_name+ " list : " + mac)

@clients.route("/deauthenticate_connected", methods=["GET"])
@logged_in
def deauthenticate_connected():
    BIN_HOSTAPDCLI = Global.EXTERNAL_TOOLS_DIR + "/hostapd-mana/hostapd/hostapd_cli"

    if "mac" not in request.args:
        return jsonify(message="mac not specified."), 400

    mac = str(request.args.get("mac"))

    HostapdCli.deauthConnected(BIN_HOSTAPDCLI, mac)
    if request.referrer:
        return redirect(request.referrer)
    return "deauthenticate : " + mac

aceweb/views/dashboard.py
from flask import Blueprint, render_template, redirect, url_for, session, request, flash
from datetime import timedelta, datetime
import psutil
from urllib2 import urlopen, URLError

from core.utils_flask import logged_in
from core.utils import HostapdCli
from core.globals import Global

dashboard = Blueprint( "dashboard", __name__)

@dashboard.route("/")
@logged_in
def show_dashboard():
    info ={}

    # get uptime
    uptime_str = None
    with open("/proc/uptime") as f:
        uptime_sec = float(f.readline().split()[0])
        dt =  datetime(1, 1 ,1) + timedelta(seconds = uptime_sec)
    info["uptime"] = "%d Hours and %d Minutes" % (dt.hour, dt.minute)

    # get connected clients
    BIN_HOSTAPDCLI = Global.EXTERNAL_TOOLS_DIR + "/hostapd-mana/hostapd/hostapd_cli"
    info["connected_clients"] = len(HostapdCli.listConnected( BIN_HOSTAPDCLI, "/tmp/aceweb/dnsmasq.leases" ))

    # Cpu usage
    info["cpu_usage"] = psutil.cpu_percent(None)

    # memory usage
    info["memory_usage"] = psutil.virtual_memory().percent

    # read public ip
    info["public_ip"] = "Not connected To Internet"

    try:
        info["public_ip"] = urlopen('http://ip.42.pl/raw').read()
    except URLError, e:
        print str(e)

    return render_template("dashboard.html", info=info)

aceweb/views/logger.py
from flask import Blueprint, render_template, redirect, url_for, session, request, flash, jsonify, send_file
import os
from core.utils_flask import logged_in
from core.utils import getLogs
from core.globals import Global

logger = Blueprint( "logger", __name__)

@logger.route("/")
@logged_in
def show_logger():
    return render_template("logger.html")

@logger.route("/fetchlogs", methods=["GET"])
@logged_in
def fetchlogs():
    log_files = {0:"/var/log/syslog", 1:"/tmp/aceweb/logs/hostapd.log",  2:"/tmp/aceweb/logs/dnsmasq.log", }

    if "log_no" not in request.args:
        return jsonify(message="'log_no' not defined"), 400


    log_no = int(request.args.get("log_no"))

    if log_no < 0 or log_no >= len(log_files):
        return jsonify( message="Invailied log number" ), 400

    if "download" not in request.args:
        logs = getLogs( log_files[log_no], 100)
        return jsonify( message=logs )

    if os.path.exists( log_files[ log_no ] ):
        return send_file(log_files[ log_no ])
    else:
        return "Logs Not Found"

aceweb/views/login.py
from flask import Blueprint, render_template, redirect, url_for, session, request, flash
from configparser import ConfigParser
import os
import bcrypt

from core.utils_flask import logged_in, flash_errors, RootUser
from core.globals import Global

login = Blueprint( "login", __name__)


# index page
@login.route("/")
@login.route("/login")
def login_index():

    form = LoginForm()
    if session.get("LOGGED_IN") is not None:
        return redirect( url_for("dashboard.show_dashboard") )
    else:
        # make sure only one root is logged in at a given time.
        if RootUser.LoggedIn == True:
            form.username.render_kw = {'disabled': 'disabled'}
            form.password.render_kw = {'disabled': 'disabled'}
            form.login.render_kw = {'disabled': 'disabled'}

            flash("Note WiFiACE only allow's one login at a time, Please logout of other devices to login from here.", "warning")

        return render_template("login.html", form=form)



@login.route("/check_login", methods=["POST"])
def check_login():
    # make sure only one root is logged in at a given time.
    if RootUser.LoggedIn == True:
        flash("Note WiFiACE only allow's one login at a time, Please logout of other devices to login from here.", "warning")
        return redirect( url_for("dashboard.show_dashboard") )

    form = LoginForm(request.form)

    if form.validate_on_submit():

        try:
            wconf = ConfigParser()
            wconf.read(Global.WIFIACE_CONF)

            username = str(wconf["core"]["username"])
            hashed_pw = str(wconf["core"]["password"])

            if  username == str(form.username.data) and bcrypt.hashpw(str(form.password.data), hashed_pw) == hashed_pw:
                session["LOGGED_IN"] = True
                flash("Logged in succesfully", "success")

                # Mark user logged in.
                RootUser.LoggedIn = True

                return redirect( url_for("dashboard.show_dashboard") )
            else:
                flash("Login Failed.", "danger")

        except Exception, e:
            flash("Configuration file error : " + str(e), "danger")
    else:
        flash_errors(form)

    return redirect( url_for("login.login_index") )

@login.route("/logout")
@logged_in
def logout():
    try:
        del session["LOGGED_IN"]
        RootUser.LoggedIn = False

        flash("Logged out succesfully", "success")
        return redirect( url_for("login.login_index") )

    except:
        flash("Login first to loggout", "warning")
        return redirect(request.referrer)



# WTForm's Classes.
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField
from wtforms.validators import DataRequired, InputRequired

class LoginForm(FlaskForm):
    username = StringField("Username", validators=[DataRequired( message = "Please enter Username")])
    password = PasswordField("Password", validators=[InputRequired(message = "Please enter Password")])
    login = SubmitField("Login")

aceweb/views/networking.py
import pyric.pyw as pyw
from flask import Blueprint, render_template, redirect, url_for, session, request, flash, jsonify
import subprocess as sb

from core.utils_flask import logged_in
from core.globals import Global
from core.networking import Wired, Wireless
from core import DN

networking = Blueprint( "networking", __name__)

@networking.route("/")
@logged_in
def show_networking():
    # auto load mymons.
    Global.monCtrl.autoLoadMymons()

    kroute = Wired.getRoute()

    wirelessInfo = []
    for w in Wireless.listInterfaces():
        info = Wireless.getInfo(w)
        c = pyw.getcard(w)

        if "monitor" in pyw.devmodes(c):
            info["inUsed"] = Global.monCtrl.isMymon(c)

        info["priority"] = Global.monCtrl.usedAs(c)
        wirelessInfo.append(info)

    wiredInfo = []
    for w in Wired.listInterfaces():
        wiredInfo.append(Wired.getInfo(w))

    return render_template("networking.html", kroute=kroute, wiredInfo=wiredInfo, wirelessInfo=wirelessInfo)


# service function's provided by networking-subdomain

# enable the given interface
@networking.route("/enable_interface", methods=["GET"])
@logged_in
def enable_interface():
    if "name" not in request.args:
        return " 'name' of the interface not specified. "

    name = str(request.args.get("name"))
    Wired.up(name)
    # redirect to the source url if called from it.
    if request.referrer:
        return redirect(request.referrer)
    return  "Enabled : "+ name


# disables the given interface
@networking.route("/disable_interface", methods=["GET"])
@logged_in
def disable_interface():
    if "name" not in request.args:
        return " 'name' of the interface not specified. "

    name = str(request.args.get("name"))
    Wired.down(name)
    # redirect to the source url if called from it.
    if request.referrer:
        return redirect(request.referrer)
    return  "Disabled : "+ name


@networking.route("/create_virtual_interface", methods=["GET"])
@logged_in
def create_virtual_interface():
    if "name" not in request.args:
        return " 'name' of the interface not specified. "

    name = str(request.args.get("name"))

    card = Wireless.createVirtualInterface(name, name + "mon")
    Global.monCtrl.addToMymons(card)

    if request.referrer:
        return redirect(request.referrer)
    return  "Created : "+ card.dev

@networking.route("/revert_virtual_interface", methods=["GET"])
@logged_in
def revert_virtual_interface():
    if "name" not in request.args:
        return " 'name' of the interface not specified. "

    name = str(request.args.get("name"))
    old_card = pyw.getcard(name)

    new_name = name
    if name.find("mon") != -1:
        new_name = name[: name.find("mon")]
    new_card = Wireless.createVirtualInterface(name, new_name)
    Global.monCtrl.delFromMymons(old_card)

    if request.referrer:
        return redirect(request.referrer)
    return  "Revert To : "+ new_card.dev

@networking.route("/set_priority", methods=["GET"])
@logged_in
def set_priority():
    if ("name" not in request.args) or ("priority" not in request.args):
        return " 'name' of the interface not specified. "

    name = str(request.args.get("name"))
    pri = int(request.args.get("priority"))

    card = pyw.getcard(name)
    if pri == 0:
        Global.monCtrl.setPrimaryMon(card)
    elif pri == 1:
        Global.monCtrl.setSecondaryMon(card)

    if request.referrer:
        return redirect(request.referrer)

    return  "Priority changed for : "+ card.dev + " : to :" + str(Global.monCtrl.usedAs(card))

@networking.route("/autoload_mymons")
@logged_in
def autoload_mymons():
    Global.monCtrl.autoLoadMymons()

    if request.referrer:
        return redirect(request.referrer)
    return  "Auto-Loaded "

@networking.route("/rfkill_unblock")
@logged_in
def rfkill_unblock():
    sb.call(["rfkill", "unblock", "all"], stdout=DN, stderr=DN)
    if request.referrer:
        return redirect(request.referrer)
    return  "rfkill unblocked all interfaces."


@networking.route("/change_mac", methods=["GET"])
@logged_in
def change_mac():

    if "iface" not in request.args:
        return jsonify(message="'iface' not provided")

    if "mac" not in request.args:
        return jsonify(message="'mac' not provided")

    iface = str(request.args.get("iface"))
    mac = str(request.args.get("mac"))

    try:
        w0 = pyw.getcard(iface)
        pyw.down(w0)
        sb.check_call(["macchanger", "-m", mac, w0.dev])
        pyw.up(w0)
    except Exception, e:
        print str(e)
        return jsonify(message="Failed to change mac addr : "), 400
    return jsonify(message="Mac Address of " + iface + " is " + mac)

@networking.route("/restore_mac", methods=["GET"])
@logged_in
def restore_mac():

    if "iface" not in request.args:
        return jsonify(message="'iface' not provided")

    iface = str(request.args.get("iface"))
    mac = Wireless.getRealMac(iface).strip()
    try:
        w0 = pyw.getcard(iface)
        pyw.down(w0)
        sb.check_call(["macchanger", "-p", w0.dev])
        pyw.up(w0)
    except Exception, e:
        print str(e)
        return jsonify(message="Failed to change mac addr : "), 400
    return jsonify(message="Mac Address of " + iface + " is " + mac)

# -----------------

aceweb/views/recon.py
from flask import Blueprint, render_template, redirect, url_for, session, request, flash, jsonify
import thread

from core.utils_flask import logged_in,resource_lock
from core.globals import Global
from core.utils import WlanScanner, Deauth

recon = Blueprint( "recon", __name__)

@recon.route("/")
@logged_in
def show_recon():
    return render_template("recon.html")

@recon.route("/start_scan", methods=["GET"])
@logged_in
def start_scan():
    if "sec" not in request.args:
        return jsonify(message="'sec' not specified."), 400

    sec = str(request.args.get("sec"))

    iface = Global.monCtrl.getAdaptor( Global.monCtrl.getSecondaryMon())

    if iface:
        try:
            Global.monCtrl.lock(iface)
            wscan = WlanScanner("ace-var", "scan-dump")
            wscan.scan(int(sec), iface.dev)
        except:
            Global.monCtrl.unLock(iface)

        else:
            Global.monCtrl.unLock(iface)
            return jsonify(result=[ ap.toJson() for ap in wscan.parseData()])

    flash("Interface not available", 'warning')
    return jsonify(message="Interface busy or not available"), 400


@recon.route("/start_deauth", methods=["GET"])
@logged_in
def start_deauth():
    # check all required parm present .
    if not all( parm in request.args for parm in ["packets", "channel", "ap_bssid"]):
        return jsonify(message="invalid parameters passed"), 400

    # check if disconnected.
    Global.monCtrl.autoLoadMymons()
    
    iface = Global.monCtrl.getAdaptor( Global.monCtrl.getSecondaryMon())
    # if interface available.
    if iface:
        # check if client_bssid specified (meaning only disconnect this client from the AP)
        client_bssid = None
        if "client_bssid" in request.args:
            client_bssid = request.args.get("client_bssid")

        packets = int(request.args.get("packets"))
        channel = int(request.args.get("channel"))
        ap_bssid = str(request.args.get("ap_bssid"))

        thread.start_new_thread(resource_lock, (iface, Deauth.deauth, packets, channel, ap_bssid, client_bssid, iface.dev))
    else:
        return jsonify("interface busy or not available."), 403

    return jsonify(message="deauth started successfully")

aceweb/templates/dashboard.html
{% extends "layout.html" %}

{% block title %} Dashboard {% endblock %}

{% block head %}
<style>

</style>
{% endblock %}

{% block body %}
<div class="page-header">
  <h1>Dashboard<small> Shows information </small></h1>
</div>

<div class="col-lg-12">

  <div class="panel panel-default col-lg-5 text-center">
    <div class="panel-body">
      <h3>{{ info['uptime'] }}</h3> <hr> <p>uptime</p>
    </div>
  </div>

  <div class="col-lg-1"></div>

  <div class="panel panel-default col-lg-5 text-center">
    <div class="panel-body">
      <h1>{{ info['connected_clients'] }}</h1> <hr> <p>Connected clients</p>
    </div>
  </div>

</div>

<div class="col-lg-12">

  <div class="panel panel-default col-lg-2 text-center">
    <div class="panel-body">
      <h1 >{{ info['cpu_usage'] }}%</h1> <hr> <small>Cpu Usage</small>
    </div>
  </div>

  <div class="col-lg-1"></div>

  <div class="panel panel-default col-lg-2 text-center">
    <div class="panel-body">
      <h1>{{ info['memory_usage'] }}%</h1> <hr> <small>memory usage</small>
    </div>
  </div>

  <div class="col-lg-1"></div>

  <div class="panel panel-default col-lg-5 text-center">
    <div class="panel-body">
      <h3>{{ info['public_ip'] }}</h3> <hr> <small>Public IP</small>
    </div>
  </div>


</div>

{% endblock %}

aceweb/templates/layout.html
<!DOCTYPE html>
<html>
   <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <title>WiFi Auditor</title>

      <!-- Bootstrap files  -->
      <link rel="stylesheet" href="{{url_for('static',filename='lib/bootstrap.min.css')}}">

      <!-- jQuery library -->
      <script src="{{url_for('static',filename='lib/jquery.min.js')}}"></script>

      <script src="{{url_for('static',filename='lib/bootstrap.min.js')}}"></script>

      <link href="{{url_for('static',filename='lib/bootstrap-toggle.min.css')}}" rel="stylesheet">
      <script src="{{url_for('static',filename='lib/bootstrap-toggle.min.js')}}"></script>

      <!-- Our Custom CSS -->
      <link rel=stylesheet type=text/css href="{{ url_for('static', filename='css/sidebar.css') }}">
      <link rel=stylesheet type=text/css href="{{ url_for('static', filename='css/layout.css') }}">
      <script type=text/javascript  src="{{ url_for('static', filename='js/init.js') }}"></script>

      <script>

         $(document).ready(function () {
             $('#sidebarCollapse').on('click', function () {
                 $('#sidebar').toggleClass('active');
             });

             $('#myModal').on('show.bs.modal', function (event) {
               var button = $(event.relatedTarget) // Button that triggered the modal
               var recipient = button.val() // Extract info from data-* attributes
               var modal = $(this)
               modal.find('.modal-title').text('New message to ' + recipient)
            })

          });

         function restart_server() {
           $.ajax({
             url: "/restart_server"
           });
           // Wait 1 second and reload page
           setTimeout(function(){
             window.location = document.URL;
           }, 1000);
         }

         function shutdown_server() {
           $.ajax({
             url: "/shutdown_server"
           });
           // Wait 1 second and reload page
           setTimeout(function(){
             window.location = "/logout";
           }, 1000);
         }


      </script>

      {% block head %}
      {% endblock %}

   </head>
   <body>
      <div class="wrapper">
         <!-- Sidebar Holder -->
         <nav id="sidebar" >
            <div class="sidebar-header">
               <h3>WiFi ACE <i class="glyphicon glyphicon-fire"></i></h3>
               <strong><i class="glyphicon glyphicon-fire"></i></strong>
            </div>
            <ul class="list-unstyled components">

               <li class="active">
                  <a href="{{ url_for('dashboard.show_dashboard') }}">
                  <i class="glyphicon glyphicon-home"></i>
                  Dashboard
                  </a>
              </li>
              <li>
                  <a href="{{ url_for('recon.show_recon') }}">
                  <i class="glyphicon glyphicon-eye-open"></i>
                  Recon
                  </a>
              </li>

              <li>
                  <a href="#rougeapSubmenu" data-toggle="collapse" aria-expanded="false">
                  <i class="glyphicon glyphicon-console"></i>
                  RougeAP options
                  </a>
                  <ul class="collapse list-unstyled" id="rougeapSubmenu">
                     <li><a href="{{ url_for('rougeap.show_rougeap') }}">Setup RougeAP</a></li>
                     <li><a href="{{ url_for('clients.show_clients') }}">Clients</a></li>
                  </ul>
               </li>

               <li>
                   <a href="#pluginSubmenu" data-toggle="collapse" aria-expanded="false">
                   <i class="glyphicon glyphicon-briefcase"></i>
                     Plugins
                   </a>
                   <ul class="collapse list-unstyled" id="pluginSubmenu">
                      <li><a href="{{ url_for('ace_plugins.show_plugins') }}">manage plugins</a></li>
                      {% for i in range(navbar|length) %}
                        <li> <a href="{{ navbar[i]['url'] }}"> {{ navbar[i]['name'] }} </a> </li>
                      {% endfor %}
                   </ul>
                </li>


               <li>
                  <a href="{{ url_for('logger.show_logger') }}">
                  <i class="glyphicon glyphicon-folder-open"></i>
                  Logger
                  </a>
               </li>
               <li>
                  <a href="{{ url_for('networking.show_networking') }}">
                  <i class="glyphicon glyphicon-sort"></i>
                  Networking
                  </a>
               </li>

               <li>
                  <a href="{{ url_for('settings.show_settings') }}">
                  <i class="glyphicon glyphicon-cog"></i>
                   Settings
                   </a>
              </li>

               <li>
                 <a href="https://bitbucket.org/a5hish/wifiace/wiki/Home" target="_blank">
                 <i class="glyphicon glyphicon-info-sign"></i>
                 Help
                 </a>
              </li>

              <li id="logout-nav">
                <hr>
                <a href="https://bitbucket.org/a5hish/wifiace/wiki/Home" target="_blank">
                <i class="glyphicon glyphicon-log-out"></i>
                Logout
                </a>
             </li>
            </ul>
         </nav>
         <!-- sidebar holder end -->
         <!-- Page Content Holder -->
        <div class="container">
          <div id="content">
             <nav class="navbar navbar-default">
                <div class="">
                   <div class="navbar-header">
                      <button type="button" id="sidebarCollapse" class="btn btn-info navbar-btn">
                      <i class="glyphicon glyphicon-align-left"></i>
                      <span>Toggle Sidebar</span>
                      </button>
                  </div>

                   <div class="collapse navbar-collapse" >

                      <ul class="nav navbar-nav navbar-right">
                         <li>
                            <a href="{{ url_for('login.logout') }}">
                            <i class="glyphicon glyphicon-log-out"></i>
                            Logout
                            </a>
                         </li>

                      </ul>
                   </div>
                </div>
             </nav>
             <div>
                <!-- Message Part -->
                  {% with messages = get_flashed_messages(with_categories=true) %}
                    {% if messages %}
                      {% for category, message in messages %}
                        <div class="alert alert-{{ category }}">{{ message }}</div>
                      {% endfor %}
                    {% endif %}
                  {% endwith %}
                <!--Ends-->
                {% block body %}
                {% endblock %}
             </div>
          </div>

        </div>
      </div>

   </body>
</html>

aceweb/templates/login.html
<html>
	<head>
		<title>login</title>
		<!-- Bootstrap files  -->
		<link rel="stylesheet" href="{{url_for('static',filename='lib/bootstrap.min.css')}}">

		<!-- jQuery library -->
		<script src="{{url_for('static',filename='lib/jquery.min.js')}}"></script>

		<script src="{{url_for('static',filename='lib/bootstrap.min.js')}}"></script>

		<style>
			body{
				background: #f5f5f5;
			}

			.panel-body{
				box-shadow: 0px 2px 8px 0px rgba(0,0,0,0.75);
			}

		</style>
	</head>
	<body>
		<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">WifiACE</a>
    </div>
  </div>
</nav>
		<div class="col-lg-12 text-center" style="height:15%;"></div>

		<div class="col-lg-4"></div>

		<div id="login" class="col-lg-4">
		<div class="panel panel-default">
		  <div class="panel-body">

        <form  method="POST" action=" {{ url_for('login.check_login') }} ">
					<h3 class="text-center">Log in to your account.</h3>
					<br><br>
					<div class="form-group">
            {{ form.username(class="form-control", placeholder="Username") }}
          </div>

          <div class="form-group">
            {{ form.password(class="form-control", placeholder="Password") }}
          </div>
					<br>
           {{ form.login(class="btn btn-info pull-right ") }}

        </form>
				<br><br>

				<!-- Message Part -->
					{% with messages = get_flashed_messages(with_categories=true) %}
						{% if messages %}
							{% for category, message in messages %}
								<div class="alert alert-{{category}}">{{ message }}</div>
							{% endfor %}
						{% endif %}
					{% endwith %}
				<!--Ends-->

		  </div>
		</div>
    </div>

		<div class="col-lg-4"></div>



	</body>
</html>